Get http://localhost:3000/

###
POST http://localhost:3000/register
Content-Type: application/json

{
    "email": "email1@gmail.com",
    "password": "pass1"
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "email1@gmail.com",
    "password": "pass1"
}

###
GET http://localhost:3000/user
Authorization: Bearer 

###
POST http://localhost:3000/create-task
Authorization: Bearer 
Content-Type: application/json

{
    "name": "task1"
}

###
GET http://localhost:3000/user
Authorization: Bearer 
